name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - run: pip install .[test] pytest-xdist
        name: Install
      - run: python3 -m pytest -n=auto --durations=50 test -W error
        name: Run unit tests
      - run: |
          python3 -m pip install matplotlib
          python3 -m pytest examples/test_examples.py -W error
        name: Run examples
